# Numpy module

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

# Creating an Array

In [3]:
a = np.array([34,343,343,343,4334])

print(a,type(a),a.dtype)

[  34  343  343  343 4334] <class 'numpy.ndarray'> int32


In [4]:
# converting list into array

l1 = [10,20,30,40.65,"dffd",60]

a = np.array(l1)

print(a,type(a),a.dtype)

['10' '20' '30' '40.65' 'dffd' '60'] <class 'numpy.ndarray'> <U32


In [5]:
print(a)

['10' '20' '30' '40.65' 'dffd' '60']


In [6]:
print(a.ndim)   #check dimension

1


In [16]:
a = np.array([12,45,6,67,78,45])


print(a,type(a))

[12 45  6 67 78 45] <class 'numpy.ndarray'>


In [17]:
# for checking the shape or values

print(a.shape)

(6,)


In [18]:
a

array([12, 45,  6, 67, 78, 45])

In [19]:
b = a.reshape(2,3)   # rows  # columns

print(b)

[[12 45  6]
 [67 78 45]]


In [20]:
b.ndim

2

In [21]:
b.shape

(2, 3)

In [22]:
b = a.reshape(3,3)

print(b)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [29]:
b = np.array([12,45,6,67,78,45,56,34,78])

In [30]:

print(b.shape,b)

(9,) [12 45  6 67 78 45 56 34 78]


In [31]:
c = b.reshape(3,3)

In [26]:
print(c)

[[12 45  6]
 [67 78 45]
 [56 34 78]]


In [27]:
print(c.ndim)

2


In [28]:
c.shape

(3, 3)

# 2D

In [32]:
ab = np.array([[34,33,34],[34,36,43],[54,54,45],[5,5,6]])

print(ab)

[[34 33 34]
 [34 36 43]
 [54 54 45]
 [ 5  5  6]]


In [33]:
ab.ndim

2

In [34]:
ab.shape

(4, 3)

In [35]:
print(ab.reshape(6,2))

[[34 33]
 [34 34]
 [36 43]
 [54 54]
 [45  5]
 [ 5  6]]


# indexing and scling in array

In [37]:
a

array([12, 45,  6, 67, 78, 45])

In [38]:
a[2]

6

In [39]:
a[-1]

45

In [40]:
a[0]

12

In [41]:
a[2:4]    # 2,3

array([ 6, 67])

In [42]:
a[:]

array([12, 45,  6, 67, 78, 45])

In [43]:
a[-4:-1]    #-4,-3,-2

array([ 6, 67, 78])

In [31]:
a[2:8:2]

array([ 6, 78])

In [ ]:
a[0:10:4]

In [ ]:
a

In [ ]:
a[0] = 100

In [ ]:
a

In [32]:
t1 = ((10,20),(30,40))

print(t1,type(t1))

a = np.array(t1)
a

((10, 20), (30, 40)) <class 'tuple'>


array([[10, 20],
       [30, 40]])

In [33]:
a.ndim

2

In [34]:
a.shape

(2, 2)

# 3D

In [45]:
t1 = ( ((10,20,15),(30,40,25)),( (50,60,18),(70,80,35) ))

print(t1,type(t1))

a=np.array(t1)


print(a)

(((10, 20, 15), (30, 40, 25)), ((50, 60, 18), (70, 80, 35))) <class 'tuple'>
[[[10 20 15]
  [30 40 25]]

 [[50 60 18]
  [70 80 35]]]


In [46]:
a.ndim

3

In [47]:
a.shape   # 12   -  3,2,2

(2, 2, 3)

In [48]:
b = a.reshape(3,2,2)

In [49]:
b

array([[[10, 20],
        [15, 30]],

       [[40, 25],
        [50, 60]],

       [[18, 70],
        [80, 35]]])

In [40]:
b.ndim

3

In [ ]:
a= np.array([1,2,3,4,5,6,7,8])
print(a,type(a))

In [ ]:
a.ndim

In [ ]:
b= a.reshape(3,4)
print(b,type(b))
print("Dimension of my array: ",b.ndim)

In [ ]:
c= a.reshape(2,2,2)
print(c,type(c))
print("Dimension of my array: ",c.ndim)

In [ ]:
c

In [ ]:
d= c.reshape(8)
d.ndim

In [ ]:
d

# arange()

In [50]:
a = np.arange(10)  # 10 - end value

print(a,type(a))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [51]:
a.ndim

1

In [53]:
a = np.arange(50,62)    # 50 - start    62-end
a

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61])

In [44]:
a.ndim


1

In [45]:
a = np.arange(10,22,2) #10-  22  2 - step size
a

array([10, 12, 14, 16, 18, 20])

In [ ]:
b = a.reshape(2,3)
b

In [ ]:
b.ndim

In [ ]:
c= a.reshape(2,3,1)
c

In [ ]:
c.ndim

In [ ]:
c.shape

# zeros()

In [46]:
a = np.zeros(5)

print(a)

[0. 0. 0. 0. 0.]


In [47]:
a.ndim

1

In [48]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
a.ndim

2

In [ ]:
a=np.zeros((2,3), dtype=int)
a

# ones()

In [5]:
a = np.ones(12)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
a.reshape(3,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
a = np.ones((4,5), dtype=int)
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
a.reshape(2,5,2)

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

# Numpy--Arithmetic Operations (OR) Matrix Operations

In [55]:

a = np.array([[10,20],[30,40]])
b = np.array([[1,2],[3,4]])

d = np.add(a,b)

print(d)

[[11 22]
 [33 44]]


In [53]:
d.ndim

2

In [ ]:
d = d.reshape(4)

print(d,d.ndim)

In [54]:
a=np.array([[10,20],[30,40]])
b=np.array([[1,2],[3,4]])

#print(a)
#print(b)

c = a + b

print(c,type(c))



[[11 22]
 [33 44]] <class 'numpy.ndarray'>


In [60]:
a = np.array([[10,20],[30,40],[34,56]])
b = np.array([[1,2],[3,4],[5,6]])

#print(a)
#print(b)

c = np.subtract(a,b)

print(c)

[[ 9 18]
 [27 36]
 [29 50]]


In [56]:
a=np.array([[10,20],[30,40]])
b=np.array([[1,2],[3,4]])

#print(a)
#print(b)

c = a - b

print(c,type(c))



[[ 9 18]
 [27 36]] <class 'numpy.ndarray'>


In [61]:
a = np.array([[10,20],[30,40]])
b = np.array([[1,2],[3,4]])

#print(a)
#print(b)

c = np.multiply(a,b)

print(c)

[[ 10  40]
 [ 90 160]]


In [62]:
a = np.array([[10,20],[30,40]])
b = np.array([[1,2],[3,4]])

#print(a)
#print(b)
c = a * b

print(c)

[[ 10  40]
 [ 90 160]]


In [63]:
a = np.array([[10,20],[30,40]])
b = np.array([[1,2],[3,4]])

#print(a)
#print(b)

c = np.divide(a,b)
print(c)

[[10. 10.]
 [10. 10.]]


In [66]:
c = a/b
print(c)

[[10. 10.]
 [10. 10.]]


In [73]:
40/4

10.0

In [74]:
a = np.array([[10,20],[30,40]])
b = np.array([[1,2],[3,4]])

#print(a)
#print(b)

c = np.floor_divide(a,b)

print(c)

10  20       1  2
30  40       3  4

[[10 10]
 [10 10]]


In [76]:
d = a//b
print(d)

[[10 10]
 [10 10]]


In [77]:
a = np.array([[11,3],[30,40]])
b = np.array([[1,2],[3,4]])

#print(a)
#print(b)

c = np.mod(a,b)

print(c)

[[0 1]
 [0 0]]


In [83]:
c = a % b
print(c)

[[0 1]
 [0 0]]


In [81]:
40 % 4

0

In [84]:
a=np.array([[10,20],[30,40]])
b=np.array([[1,2],[3,4]])
 
#print(a)
#print(b)

c = np.power(a,b)

print(c)

[[     10     400]
 [  27000 2560000]]


In [87]:
c = a ** b
c

array([[     10,     400],
       [  27000, 2560000]])

In [ ]:
10**1

In [85]:
# 20 **2 = 20 * 20

20 ** 2



400

In [ ]:
# 30 ** 3 = 30 * 30 * 30

In [86]:
30 ** 3

27000

# 3D

In [88]:
l1 = [[[10,20],[30,40]],[[20,23],[60,45]]]
l2 = [[[1,2],[3,4]],[[5,8],[45,50]]]

a = np.array(l1)
b = np.array(l2)

d = np.add(a,b)

print(d)

[[[ 11  22]
  [ 33  44]]

 [[ 25  31]
  [105  95]]]


In [89]:
d.shape

(2, 2, 2)

In [90]:
d = d.reshape(8)
d

array([ 11,  22,  33,  44,  25,  31, 105,  95])

In [93]:
d.ndim

1

# 1D

In [97]:
l1 = [ 11,  22,  33,  44,  25,  31, 105,  95]
l2 = [1,2,3,4,5,6,7,87.8]

a = np.array(l1)
b = np.array(l2)

d = np.add(a,b)

print(d)

[ 12.   24.   36.   48.   30.   37.  112.  182.8]
